# Generated by Django 5.2.1 on 2025-05-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("position", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("date_joined", models.DateField(auto_now_add=True)),
                ("promoted", models.BooleanField(default=False)),
            ],
        ),
    ]
